# action.yml
name: 'Create PR with metadta'
description: 'Action to automatically create PR to keep two branches in sync.'
author: 'Poorva Gokhale'
icon: 'git-pull-request'
color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'
